spring.datasource: 
  driver-class-name: org.h2.Driver
  url: 'jdbc:h2:file:~/.h2/celloud-demos'
  username: celloud
  password: CelLoud1010
spring.h2.console:
  path: /h2-console
  enabled: true
  settings.web-alow-others: true
spring.jpa: 
  hibernate.ddl-auto: update
  show-sql: true
spring:
    jackson.default-property-inclusion: non_null